# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" and "major" version upgrades.
versions = ["minor", "patch", "major"]
usernames = ["dependabot"]
